apiVersion: v1
kind: Service
metadata:
  name: lab4-postgres
  labels:
    app: lab4
    component: db
spec:
  type: ClusterIP
  selector:
    app: lab4
    component: db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
